version: '3'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment: 
      - NODE_ENV=development

    
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - api